### ISSUE TITLE
Use both subnets in configuration

### ISSUE THREAD

**Issue by kbeamnsidc** [asfadmin/CIRRUS-core#7]
The `cumulus/main.tf` looks up the VPC and Subnet IDs, but only uses the first subnet. I did this as a temporary fix of a problem with deploying using both subnet IDs. I don't actually remember what the issue was. So: see if it's still an issue if we use both subnets, and resolve it!

**Comment by amarouane-ABDELHAK** [comment]
Actually I am having the same problem with the PR I opened fr cumulus-template. We only need one subnet (they are 3 in general) the tag name of the ones we want are different but there name is "Application subnet <region>"  where <region> can be us-east-1a us-east-1b or us-east-1c (assuming us-east region used). I don't know if we can pull the data source with tag contains instead of equal.

**Comment by kbeamnsidc** [comment]
Fixed by #12
